# Generated by Django 4.2.3 on 2023-07-04 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_productmodel_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='sku',
            field=models.CharField(blank=True, default='', help_text='format: required, max_length=50', max_length=50, null=True, verbose_name='Stock Keeping Unit'),
        ),
    ]
