import os

import django


#  you have to set the correct path to you settings module
os.environ.setdefault("DJANGO_SETTINGS_MODULE", "izas.settings.dev")
django.setup()

from colors.models import Color

colors = [
    {'code': 'AL', 'name': 'ALUMINIO', 'pantone_name': '', 'pantone_chart_code': '', 'hex_color': '#000000', 'red': 0,
     'green': 0, 'blue': 0},
    {'code': 'CE', 'name': 'CERAMIC', 'pantone_name': 'CERAMIC', 'pantone_chart_code': 'pantone-16-5127-tcx',
     'hex_color': '#00aaa9', 'red': 0, 'green': 170, 'blue': 169},
    {'code': 'AR', 'name': 'ARMY', 'pantone_name': 'DUSKY GREEN', 'pantone_chart_code': 'pantone-17-0517-tpx',
     'hex_color': '#78705e', 'red': 120, 'green': 112, 'blue': 94},
    {'code': 'AT', 'name': 'ATLANTIC', 'pantone_name': 'ATLANTIC DEEP', 'pantone_chart_code': 'pantone-19-4726-tcx',
     'hex_color': '#274e55', 'red': 39, 'green': 78, 'blue': 85},
    {'code': 'BB', 'name': 'BARBERRY', 'pantone_name': 'BARBERRY', 'pantone_chart_code': 'pantone-18-1760-tpx',
     'hex_color': '#b61745', 'red': 182, 'green': 23, 'blue': 69},
    {'code': 'BG', 'name': 'BEIGE', 'pantone_name': '', 'pantone_chart_code': '', 'hex_color': '#000000', 'red': 0,
     'green': 0, 'blue': 0},
    {'code': 'BK', 'name': 'BLACK', 'pantone_name': 'JET BLACK', 'pantone_chart_code': 'pantone-19-0303-tcx',
     'hex_color': '#2d2c2f', 'red': 45, 'green': 44, 'blue': 47},
    {'code': 'BL', 'name': 'BLUE', 'pantone_name': 'PARISIAN BLUE', 'pantone_chart_code': 'pantone-18-4036-tcx',
     'hex_color': '#4f7ca4', 'red': 79, 'green': 124, 'blue': 164},
    {'code': 'BM', 'name': 'BLUEMOON', 'pantone_name': 'INIGNIA BLUE', 'pantone_chart_code': 'pantone-19-4028-tcx',
     'hex_color': '#2f3e55', 'red': 47, 'green': 62, 'blue': 85},
    {'code': 'BR', 'name': 'BEET RED', 'pantone_name': 'BEET RED', 'pantone_chart_code': 'pantone-19-2030-tpx',
     'hex_color': '#7f2a49', 'red': 127, 'green': 42, 'blue': 73},
    {'code': 'BW', 'name': 'BROWN', 'pantone_name': '', 'pantone_chart_code': '', 'hex_color': '#000000', 'red': 0,
     'green': 0, 'blue': 0},
    {'code': 'BV', 'name': 'BLUE RIVER', 'pantone_name': 'BLUE ASTER', 'pantone_chart_code': 'pantone-18-4252-tpx',
     'hex_color': '#007bbd', 'red': 0, 'green': 123, 'blue': 189},
    {'code': 'C2', 'name': 'CAKI II', 'pantone_name': 'OLIVE BRANCH', 'pantone_chart_code': 'pantone-18-0527-tpx',
     'hex_color': '#706f48', 'red': 112, 'green': 111, 'blue': 72},
    {'code': 'CB', 'name': 'CORONET BLUE', 'pantone_name': '', 'pantone_chart_code': '', 'hex_color': '#000000',
     'red': 0, 'green': 0, 'blue': 0},
    {'code': 'CF', 'name': 'CORAL FLUOR', 'pantone_name': 'FIERY CORAL', 'pantone_chart_code': 'pantone-15-1456-tn',
     'hex_color': '#ff4f58', 'red': 255, 'green': 79, 'blue': 88},
    {'code': 'CH', 'name': 'CHARCOAL', 'pantone_name': 'CARCOAL GREY', 'pantone_chart_code': 'pantone-18-0601-tcx',
     'hex_color': '#6c6868', 'red': 108, 'green': 104, 'blue': 104},
    {'code': 'CK', 'name': 'CAKI', 'pantone_name': 'PESTO', 'pantone_chart_code': 'pantone-18-0228-tcx',
     'hex_color': '#595f34', 'red': 89, 'green': 95, 'blue': 52},
    {'code': 'CL', 'name': 'CELESTIAL', 'pantone_name': 'CELESTIAL', 'pantone_chart_code': 'pantone-18-4530-tpx',
     'hex_color': '#066b8b', 'red': 6, 'green': 107, 'blue': 139},
    {'code': 'CT', 'name': 'CHOCLOATE', 'pantone_name': 'AFTER DARK', 'pantone_chart_code': 'pantone-19-1101-tcx',
     'hex_color': '#3c3535', 'red': 60, 'green': 53, 'blue': 53},
    {'code': 'D2', 'name': 'DARK AQUA II', 'pantone_name': 'INK BLUE', 'pantone_chart_code': 'pantone-19-4234-tpx',
     'hex_color': '#16576f', 'red': 22, 'green': 87, 'blue': 111},
    {'code': 'DA', 'name': 'DARK AGUA', 'pantone_name': 'SHADED SPRUCE', 'pantone_chart_code': 'pantone-19-4524-tpx',
     'hex_color': '#005960', 'red': 0, 'green': 89, 'blue': 96},
    {'code': 'DB', 'name': 'DARK BLUEMOON', 'pantone_name': '', 'pantone_chart_code': '', 'hex_color': '#000000',
     'red': 0, 'green': 0, 'blue': 0},
    {'code': 'DW', 'name': 'DARK BROWN', 'pantone_name': '', 'pantone_chart_code': '', 'hex_color': '#000000', 'red': 0,
     'green': 0, 'blue': 0},
    {'code': 'DC', 'name': 'DARK CAKI', 'pantone_name': 'OLIVE BRANCH', 'pantone_chart_code': 'pantone-18-0527-tcx',
     'hex_color': '#dd5ffc', 'red': 221, 'green': 95, 'blue': 252},
    {'code': 'DG', 'name': 'DARK GREY', 'pantone_name': '', 'pantone_chart_code': '', 'hex_color': '#000000', 'red': 0,
     'green': 0, 'blue': 0},
    {'code': 'DP', 'name': 'DARK PURPLE', 'pantone_name': '', 'pantone_chart_code': '', 'hex_color': '#000000',
     'red': 0, 'green': 0, 'blue': 0},
    {'code': 'DQ', 'name': 'DARK AQUA', 'pantone_name': '', 'pantone_chart_code': '', 'hex_color': '#000000', 'red': 0,
     'green': 0, 'blue': 0},
    {'code': 'DV', 'name': 'DIVA PINK', 'pantone_name': 'DIVA PINK', 'pantone_chart_code': 'pantone-16-1650-tn',
     'hex_color': '#ff1659', 'red': 255, 'green': 22, 'blue': 89},
    {'code': 'FA', 'name': 'FAIR AQUA', 'pantone_name': 'FAIR AQUA', 'pantone_chart_code': 'pantone-12-5409-tpx',
     'hex_color': '#bfe9e3', 'red': 191, 'green': 233, 'blue': 227},
    {'code': 'FX', 'name': 'FUCSIA', 'pantone_name': 'BEETROOT PURPLE', 'pantone_chart_code': 'pantone-18-2143-tcx',
     'hex_color': '#cf2d71', 'red': 207, 'green': 45, 'blue': 113},
    {'code': 'GH', 'name': 'GOLD HONEY', 'pantone_name': 'HONEY GOLD', 'pantone_chart_code': 'pantone-15-1142-tpx',
     'hex_color': '#d5a149', 'red': 213, 'green': 161, 'blue': 73},
    {'code': 'GN', 'name': 'GREEN', 'pantone_name': 'GREEEN FLASH', 'pantone_chart_code': 'pantone-15-0146-tpx',
     'hex_color': '#71cc51', 'red': 113, 'green': 204, 'blue': 81},
    {'code': 'HO', 'name': 'HONEY', 'pantone_name': 'HONEY', 'pantone_chart_code': 'pantone-16-0946-tcx',
     'hex_color': '#ba9238', 'red': 186, 'green': 146, 'blue': 56},
    {'code': 'IL', 'name': 'ILLUMINATING', 'pantone_name': 'ILLUMINATING', 'pantone_chart_code': 'pantone-13-0647-tcx',
     'hex_color': '#F5DF4D', 'red': 245, 'green': 223, 'blue': 77},
    {'code': 'JA', 'name': 'JARDIN', 'pantone_name': 'FORMAL GARDEN', 'pantone_chart_code': 'pantone-19-6350-tcx',
     'hex_color': '#1F5129', 'red': 31, 'green': 81, 'blue': 41},
    {'code': 'JD', 'name': 'JADE', 'pantone_name': 'GRAYED JADE', 'pantone_chart_code': 'pantone-14-6011-tpx',
     'hex_color': '#9bc2ac', 'red': 155, 'green': 194, 'blue': 172},
    {'code': 'LG', 'name': 'LIGHT GREEN', 'pantone_name': 'JASMINE GREEN', 'pantone_chart_code': 'pantone-15-0545-tcx',
     'hex_color': '#7ec845', 'red': 126, 'green': 200, 'blue': 69},
    {'code': 'LB', 'name': 'LIGHT BLUE', 'pantone_name': 'STONEWASH', 'pantone_chart_code': 'pantone-17-3917-tcx',
     'hex_color': '#74809a', 'red': 116, 'green': 128, 'blue': 154},
    {'code': 'L2', 'name': 'LIGHT BLUE', 'pantone_name': 'ILLUSION BLUE', 'pantone_chart_code': 'pantone-13-4103-tpx',
     'hex_color': '#cad7e0', 'red': 202, 'green': 215, 'blue': 224},
    {'code': 'LT', 'name': 'LOTUS', 'pantone_name': 'LOTUS', 'pantone_chart_code': 'pantone-14-1905-tpx',
     'hex_color': '#e5c3c3', 'red': 229, 'green': 195, 'blue': 195},
    {'code': 'LY', 'name': 'LIGHT YELLOW', 'pantone_name': 'LIMELIGHT', 'pantone_chart_code': 'pantone-12-0740-tcx',
     'hex_color': '#f0e87d', 'red': 240, 'green': 232, 'blue': 125},
    {'code': 'MA', 'name': 'MANGO', 'pantone_name': 'ICED MANG', 'pantone_chart_code': 'pantone-14-1140-ts',
     'hex_color': '#ffad4f', 'red': 255, 'green': 173, 'blue': 79},
    {'code': 'MR', 'name': 'MINERAL RED', 'pantone_name': 'TAWNY PORT', 'pantone_chart_code': 'pantone-19-1725-tcx',
     'hex_color': '#5c2c35', 'red': 92, 'green': 44, 'blue': 53},
    {'code': 'MT', 'name': 'MENTA', 'pantone_name': 'HONEYDEW', 'pantone_chart_code': 'pantone-12-5808-tcx',
     'hex_color': '#bae1d3', 'red': 186, 'green': 225, 'blue': 211},
    {'code': 'NT', 'name': 'NATURAL', 'pantone_name': 'NATURAL', 'pantone_chart_code': 'pantone-16-1310-tcx',
     'hex_color': '#aa907d', 'red': 170, 'green': 144, 'blue': 125},
    {'code': 'NV', 'name': 'NAVY BLUE', 'pantone_name': 'MOOED INDIGO', 'pantone_chart_code': 'pantone-19-4025-tpx',
     'hex_color': '#6a6a45', 'red': 106, 'green': 106, 'blue': 69},
    {'code': 'OJ', 'name': 'OR JUSTA', 'pantone_name': 'FAIR ORCHID', 'pantone_chart_code': 'pantone-15-3508-tpx',
     'hex_color': '#c1acc5', 'red': 193, 'green': 172, 'blue': 197},
    {'code': 'OQ', 'name': 'ORQUIDEA', 'pantone_name': 'DEEP ORCHID', 'pantone_chart_code': 'pantone-18-3022-tpx',
     'hex_color': '#94417b', 'red': 148, 'green': 65, 'blue': 123},
    {'code': 'OR', 'name': 'ORANGE', 'pantone_name': 'AUTUMN GLORY', 'pantone_chart_code': 'pantone-15-1263-tcx',
     'hex_color': '#ff8812', 'red': 255, 'green': 136, 'blue': 18},
    {'code': 'SV', 'name': 'SILVER', 'pantone_name': 'GLACIER GREY', 'pantone_chart_code': 'pantone-14-4102-tcx',
     'hex_color': '#c5c6c7', 'red': 197, 'green': 198, 'blue': 199},
    {'code': 'PE', 'name': 'PEACH', 'pantone_name': 'PEACH NECTAR', 'pantone_chart_code': 'pantone-14-1228-tcx',
     'hex_color': '#ffb59b', 'red': 255, 'green': 181, 'blue': 155},
    {'code': 'RD', 'name': 'RED', 'pantone_name': 'TOMATO', 'pantone_chart_code': 'pantone-18-1660-tcx',
     'hex_color': '#ce2939', 'red': 206, 'green': 41, 'blue': 57},
    {'code': 'RS', 'name': 'ROSE', 'pantone_name': 'ORCHID SMOKE', 'pantone_chart_code': 'pantone-15-2210-tpx',
     'hex_color': '#d194ae', 'red': 209, 'green': 148, 'blue': 174},
    {'code': 'RY', 'name': 'ROYAL', 'pantone_name': 'TWILIGHT BLUE', 'pantone_chart_code': 'pantone-19-3938-tcx',
     'hex_color': '#313d64', 'red': 49, 'green': 61, 'blue': 100},
    {'code': 'RY', 'name': 'ROYAL', 'pantone_name': 'DIRECTOIRE BLUE', 'pantone_chart_code': 'pantone-18-4244-tpx',
     'hex_color': '#0067ad', 'red': 0, 'green': 103, 'blue': 173},
    {'code': 'SM', 'name': 'SMOKE', 'pantone_name': 'EBONY', 'pantone_chart_code': 'pantone-19-4104-tpx',
     'hex_color': '#3d4249', 'red': 61, 'green': 66, 'blue': 73},
    {'code': 'SP', 'name': 'SPRING', 'pantone_name': 'SULPHUR SPRING', 'pantone_chart_code': 'pantone-13-0650-tcx',
     'hex_color': '#d5d717', 'red': 213, 'green': 215, 'blue': 23},
    {'code': 'ST', 'name': 'STONE', 'pantone_name': 'SYMPLE TAUPE', 'pantone_chart_code': 'pantone-16-0906-tcx',
     'hex_color': '#ad9f93', 'red': 173, 'green': 159, 'blue': 147},
    {'code': 'TQ', 'name': 'TURQUOISE', 'pantone_name': 'HAWAIIAN OCEAN', 'pantone_chart_code': 'pantone-17-4540-tcx',
     'hex_color': '#008db9', 'red': 0, 'green': 141, 'blue': 185},
    {'code': 'WH', 'name': 'WHITE', 'pantone_name': 'BRIGHT WHITE', 'pantone_chart_code': 'pantone-11-0601-tpx',
     'hex_color': '#f1f2f1', 'red': 241, 'green': 242, 'blue': 241},
    {'code': 'YF', 'name': 'YELLOW FLUOR', 'pantone_name': 'SAFETY YELLOW', 'pantone_chart_code': 'pantone-13-0630-tn',
     'hex_color': '#edff00', 'red': 237, 'green': 255, 'blue': 0},

]

for color in colors:
    x, c = Color.objects.get_or_create(
        code=color['code'],
        name=color['name'],
        pantone_name=color['pantone_name'],
        pantone_chart_code=color['pantone_chart_code'],
        hex_color=color['hex_color'],
        red=color['red'],
        blue=color['blue'],
        green=color['green'],
    )
    print(x)
    if c:
        print("created")
