<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// phpcs:disable Magento2.Templates.ThisInTemplate
// phpcs:disable Squiz.PHP.GlobalKeyword.NotAllowed
?>

<?php
    $_order  = $block->getOrder();
    $_source = $block->getSource();
    $_fullInfo = $this->helper(\Magento\Tax\Helper\Data::class)->getCalculatedTaxes($_source);
    global $taxIter;
    $taxIter++;
?>

<?php if ($_fullInfo && $block->displayFullSummary()) : ?>
        <?php foreach ($_fullInfo as $info) : ?>
            <?php
                $percent    = $info['percent'];
                $amount     = $info['tax_amount'];
                $baseAmount = $info['base_tax_amount'];
                $title      = $info['title'];
            ?>
            <tr class="totals tax details details-<?= (int) $taxIter ?><?= ($block->getIsPlaneMode()) ? ' plane' : '' ?>">
                <td <?= /* @noEscape */ $block->getLabelProperties() ?> style="text-align:right; padding-right:16px">
                    <?= $block->escapeHtml($title) ?>
                    <?php if ($percent !== null) : ?>
                        (<?= (float) $percent ?>%)
                    <?php endif; ?>
                    <br />
                </td>
                <td <?= /* @noEscape */ $block->getValueProperties() ?> rowspan="1" style="text-align:right; padding-right:16px">
                    <?= /* @noEscape */ $_order->formatPrice($amount) ?>
                </td>
            </tr>
        <?php endforeach; ?>
<?php endif; ?>
<?php if ($block->displayFullSummary() && $_fullInfo && !$block->getIsPlaneMode()) : ?>
<tr class="totals-tax-summary">
<?php elseif ($block->displayFullSummary() && $_fullInfo && $block->getIsPlaneMode()) : ?>
<tr class="totals-tax-summary plane">
<?php else : ?>
<tr class="totals-tax">
<?php endif; ?>
    <!-- <th <?php /* @noEscape */// $block->getLabelProperties() ?> scope="row" style="text-align:right; padding-right:16px">
        <?php //if ($block->displayFullSummary()) : ?>
            <div class="detailed"><?php // $block->escapeHtml(__('Tax')) ?></div>
        <?php //else : ?>
            <?php // $block->escapeHtml(__('Tax')) ?>
        <?php //endif; ?>
    </th> -->
    <!-- <td style="text-align:right; padding-right:16px" <?php /* @noEscape */ //$block->getValueProperties() ?> data-th="<?php //= $block->escapeHtmlAttr(__('Tax')) ?>">
        <strong><?php /* @noEscape */ //$_order->formatPrice($_source->getTaxAmount()) ?></strong>
    </td> -->
</tr>
