<?php
// @codingStandardsIgnoreFile
$blockObj = $block->getLayout()->createBlock('Magento\Customer\Block\Account\Customer');
?>
<div class="conditions">
    <input type="checkbox" checked="checked" name="confirm_conditions" id="confirm-conditions" data-role="confirm-conditions" value="1" title="Confirmar condiciones" class="checkbox">
    <label class="label-form" for="confirm-conditions"><span>He leído y acepto los <a target="_blank" href="" >Términos y Condiciones</a> de Izas-Outdoor. </span></label>
</div>
<?php if ($block->isPossibleOnepageCheckout()):?>
    <?php if ($blockObj->customerLoggedIn()):?>
        <button type="button"
                data-role="proceed-to-checkout"
                disabled="disabled"
                title="<?= /* @escapeNotVerified */ __('Proceed to Checkout') ?>"
                data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"<?= /* @escapeNotVerified */ $block->getCheckoutUrl() ?>"}}'
                class="action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
                <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
            <span><?= /* @escapeNotVerified */ __('Checkout') ?></span>
        </button>
    <?php endif?>
    <?php if (!$blockObj->customerLoggedIn()):?>
        <button type="button"
                data-role="proceed-to-checkout"
                disabled="disabled"
                title="<?= /* @escapeNotVerified */ __('Proceed to Checkout') ?>"
                data-mage-init='{"Magento_Checkout/js/proceed-to-checkout":{"checkoutUrl":"/customer/account/login?origin=checkout"}}'
                class="action primary checkout<?= ($block->isDisabled()) ? ' disabled' : '' ?>"
                <?php if ($block->isDisabled()):?>disabled="disabled"<?php endif; ?>>
            <span><?= /* @escapeNotVerified */ __('Checkout') ?></span>
        </button>
    <?php endif?>
<?php endif?>
<div>
    <span><?= /* @escapeNotVerified */ __('Accepted payment methods') ?></span>
    <img src="<?php echo $this->getViewFileUrl('img/payement_type.png'); ?>">
</div>
