<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Wishlist\Block\Customer\Wishlist\Item\Column\Edit $block */

/** @var \Magento\Wishlist\Model\Item $item */
$item = $block->getItem();
$product = $item->getProduct();
?>

<?php if ($product->isVisibleInSiteVisibility()): ?>
    <!--<a class="track-order action edit" href="<?= $block->escapeUrl($block->getItemConfigureUrl($item)) ?>">
        <span><?= $block->escapeHtml(__('Edit')) ?></span>
    </a>-->
    <button type="submit" name="do" title="<?= $block->escapeHtmlAttr(__('Update Wish List')) ?>" class="action update">
        <span><?= $block->escapeHtml(__('Update Wish List')) ?></span>
    </button>
<?php endif ?>
