<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
?>

<br><br><br><br>
<div style="text-align:center">
<img src="https://es.izas-outdoor.com/media/logo/default/logo.png" title="Izas" alt="Izas">
<div><br>
<h1 style="text-align:center">Estamos de mantenimiento!</h1>
<p style="text-align:center">
   Queremos mejorar tu experiencia con nosotros y por ese motivo estamos realizando cambios en nuestra web. <br><br>

Disculpa las molestias, en breve reabriremos nuestras puertas!<br><br>

El equipo de IZAS</p>
