<?php
/**@var \Magento\Framework\View\Element\Template $block */
?>
<div data-block="top-links" class="top-links hidden-lg-up col-3">
    <div class="top-link profile">
            <a href="<?= $block->getUrl('customer/account'); ?>"><span class="icon-profile"></span></a>
    </div>
    <div class="top-link search">
        <a href="#"><span class="icon-recherche"></span></a>
    </div>
    <div class="top-link basket" data-bind="scope: 'toplink_minicart_content'">
        <a class="action showcart" href="<?= $block->getUrl('checkout/cart'); ?>">
            <span></span>
        </a>
        <a href="<?= $block->getUrl('checkout/cart'); ?>" class="qty">
            <span class="counter-number"><!-- ko text: getCartParam('summary_count') --><!-- /ko --></span>
        </a>
    </div>
</div>
<script type="text/x-magento-init">
    {
        "[data-block='top-links']": {
            "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */ $block->getJsLayout() ?>
        }
    }
</script>