# Generated by Django 4.2.3 on 2023-07-24 22:57

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields
import modelcluster.fields
import wagtailmenus.models.menuitems


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0083_workflowcontenttype'),
        ('wagtailmenus', '0024_alter_flatmenuitem_options_alter_mainmenu_options_and_more'),
        ('wagtailimages', '0025_alter_image_file_alter_rendition_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='IzasMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='En este campo se muestra el título del IzasMenu', max_length=100, verbose_name='IzasMenu title')),
                ('slug', django_extensions.db.fields.AutoSlugField(blank=True, editable=False, help_text='En este campo se muestra el slug del IzasMenu', populate_from='title', verbose_name='IzasMenu slug')),
            ],
            options={
                'verbose_name': 'IzasMenu',
                'verbose_name_plural': 'IzasMenus',
            },
        ),
        migrations.CreateModel(
            name='IzasMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_title', models.CharField(blank=True, help_text='En este campo se muestra el link del titulo del IzasMenuItem', max_length=50, null=True, verbose_name='IzasMenuItem link_title')),
                ('link_url', models.CharField(blank=True, help_text='En este campo se muestra el link url del IzasMenuItem', max_length=500, verbose_name='IzasMenuItem link_url')),
                ('open_in_new_tab', models.BooleanField(blank=True, default=False, help_text='En este campo se muestra cómo se abre una pestaña en IzasMenuItem', verbose_name='IzasMenuItem open_in_new_tab')),
                ('link_page', models.ForeignKey(blank=True, help_text='En este campo se muestra el link de la página del IzasMenuItem', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.page', verbose_name='IzasMenuItem link_page')),
                ('page', modelcluster.fields.ParentalKey(help_text='En este campo se muestra la pagina de IzasMenuItem', on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='menus.izasmenu', verbose_name='IzasMenuItem page')),
            ],
            options={
                'verbose_name': 'IzasMenuItem',
                'verbose_name_plural': 'IzasMenuItems',
            },
        ),
        migrations.CreateModel(
            name='CustomMainMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('link_url', models.CharField(blank=True, help_text='En este campo se muestra el link_url del menuItem', max_length=255, null=True, verbose_name='link to a custom URL')),
                ('url_append', models.CharField(blank=True, help_text="Use this to optionally append a #hash or querystring to the above page's URL.", max_length=255, verbose_name='append to URL')),
                ('handle', models.CharField(blank=True, help_text='Use this field to optionally specify an additional value for each menu item, which you can then reference in custom menu templates.', max_length=100, verbose_name='handle')),
                ('link_text', models.CharField(blank=True, help_text="Provide the text to use for a custom URL, or set on an internal page link to use instead of the page's title.", max_length=255, verbose_name='link text')),
                ('allow_subnav', models.BooleanField(default=True, help_text="NOTE: The sub-menu might not be displayed, even if checked. It depends on how the menu is used in this project's templates.", verbose_name='allow sub-menu for this item')),
                ('hover_description', models.CharField(blank=True, help_text='En este campo se muestra la hover_description del menu de CustomMainMenuItem', max_length=250, verbose_name='CustomMainMenuItem hover_description')),
                ('image', models.ForeignKey(blank=True, help_text='En este campo se muestra la imagen del menu del CustomMainMenuItem', null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailimages.image', verbose_name='CustomMainMenuItem image')),
                ('link_page', models.ForeignKey(blank=True, help_text='En este campo se muestra el menu abstracto del menuItem', null=True, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.page', verbose_name='link to an internal page')),
                ('menu', modelcluster.fields.ParentalKey(help_text='En este campo se muestra el menu del CustomMainMenuItem', on_delete=django.db.models.deletion.CASCADE, related_name='izas_menu_items', to='wagtailmenus.mainmenu', verbose_name='CustomMainMenuItem menu')),
            ],
            options={
                'verbose_name': 'CustomMainMenuItem',
                'verbose_name_plural': 'CustomMainMenuItems',
            },
            bases=(models.Model, wagtailmenus.models.menuitems.MenuItem),
        ),
    ]
