<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Address\Book $block */
?>
<h1 class="title_form"><?php echo __('MY SAVED ADDRESSES') ?></h1>
<div class="form_information block block-addresses-default">
    <div class="block-content">
        <?php if ($_pAddsses = $block->getDefaultBilling()): ?>
            <div class="box box-address-billing">
                <strong class="box-title">
                    <span><?= $block->escapeHtml(__('Default Billing Address')) ?></span>
                </strong>
                <div class="option_input_groupe">
                <div class="box-content">
                    <address class="adresse-box">
                        <?= $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                        <div class="footer-adresse">
                            <a href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>" class="edit-btn"><i class="fas fa-pen"></i><span><?= $block->escapeHtml(__('Edit Address')) ?></span></a>
                            </div>
                    </address>
                </div>
                <!--<div class="box-actions">
                    <a class="action edit" href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>">
                        <span class="edit_addresse"><?= $block->escapeHtml(__('Change Billing Address')) ?></span>
                    </a>
                </div>-->
              </div>
            </div>
        <?php else: ?>
            <div class="box box-billing-address">
                <strong class="box-title"><span><?= $block->escapeHtml(__('Default Billing Address')) ?></span></strong>
                <div class="box-content">
                    <p><?= $block->escapeHtml(__('You have no default billing address in your address book.')) ?></p>
                </div>
            </div>
        <?php endif ?>

        <?php if ($_pAddsses = $block->getDefaultShipping()): ?>
            <strong class="box-title">
                <span><?= $block->escapeHtml(__('Default Shipping Address')) ?></span>
            </strong>
            <div class="option_input_groupe box box-address-shipping">
                <div class="box-content">
                    <address class="adresse-box">
                        <?= $block->getAddressHtml($block->getAddressById($_pAddsses)) ?>
                        <div class="footer-adresse">
                            <a href="<?= $block->escapeUrl($block->getAddressEditUrl($_pAddsses)) ?>" class="edit-btn"><i class="fas fa-pen"></i><span><?= $block->escapeHtml(__('Edit Address')) ?></span></a>
                              </div>
                    </address>
                </div>
                <!--<div class="box-actions">
                    <a class="action edit" href="">
                        <span class="edit_addresse"><?= $block->escapeHtml(__('Change Shipping Address')) ?></span>
                    </a>
                </div>-->
            </div>
        <?php else: ?>
            <div class="box box-shipping-address">
                <strong class="box-title"><span><?= $block->escapeHtml(__('Default Shipping Address')) ?></span></strong>
                <div class="box-content">
                    <p><?= $block->escapeHtml(__('You have no default shipping address in your address book.')) ?></p>
                </div>
            </div>
        <?php endif ?>
    </div>
</div>
<!--
<div class="form_information block block-addresses-default">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Additional Address Entries')) ?></strong></div>
    <div class="block-content">
        <?php if ($_pAddsses = $block->getAdditionalAddresses()): ?>
                <?php foreach ($_pAddsses as $_address): ?>

                        <address class="adresse-box">
                            <?= $block->getAddressHtml($_address) ?><br />
                            <div class="footer-adresse">
                                <a href="<?= $block->escapeUrl($block->getUrl('customer/address/edit', ['id' => $_address->getId()])) ?>" class="edit-btn"><i class="fas fa-pen"></i><span><?= $block->escapeHtml(__('Edit Address')) ?></span></a>
                                <a class="add-address" href="#" role="delete-address" data-address="<?= $block->escapeHtmlAttr($_address->getId()) ?>"><span><?= $block->escapeHtml(__('Delete Address')) ?></span></a>
                              </div>
                        </address>
                        <!--<div class="item actions">
                            <a class="action edit" href="<?= $block->escapeUrl($block->getUrl('customer/address/edit', ['id' => $_address->getId()])) ?>"><span class="edit_addresse"><?= $block->escapeHtml(__('Edit Address')) ?></span></a>
                            <a class="action delete" href="#" role="delete-address" data-address="<?= $block->escapeHtmlAttr($_address->getId()) ?>"><span><?= $block->escapeHtml(__('Delete Address')) ?></span></a>
                        </div>-->

                <?php endforeach; ?>

        <?php else: ?>
            <p class="empty"><?= $block->escapeHtml(__('You have no other address entries in your address book.')) ?></p>
        <?php endif ?>
    </div>
</div>-->

<div class="actions-toolbar">
    <div class="primary">
        <button type="button" role="add-address" title="<?= $block->escapeHtmlAttr(__('Add New Address')) ?>" class="add-address action primary add"><span><?= $block->escapeHtml(__('Add New Address')) ?></span></button>
    </div>
</div>
<script type="text/x-magento-init">
    {
        ".content_account": {
            "address": {
                "deleteAddress": "a[role='delete-address']",
                "deleteUrlPrefix": "<?= $block->escapeJs($block->escapeUrl($block->getDeleteUrl())) ?>id/",
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?= $block->escapeJs($block->escapeUrl($block->getAddAddressUrl())) ?>"
            }
        }
    }
</script>
