<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Address\Grid $block */
$customerAddressView = $block->getData('customer_address');
?>

<div class="block block-addresses-list">
    <div class="block-title"><strong><?= $block->escapeHtml(__('Additional Address Entries')) ?></strong></div>
    <div class="block-content">
        <?php if ($_pAddsses = $block->getAdditionalAddresses()): ?>

            <div class="table-wrapper additional-addresses">
                <div class="data table table-additional-addresses-items history" id="additional-addresses-table">
                    <strong class="box-title"><?= /* @escapeNotVerified */ __('Additional addresses') ?></strong>

                    <?php foreach ($_pAddsses as $address): ?>
                        <address class="adresse-box">
                            <?= $block->escapeHtml(__('First Name')) ?> : <?= $block->escapeHtml($address->getFirstname()) ?></br>
                            <?= $block->escapeHtml(__('Last Name')) ?> : <?= $block->escapeHtml($address->getLastname()) ?></br>
                            <?= $block->escapeHtml(__('Street Address')) ?> : ><?= $block->escapeHtml($block->getStreetAddress($address)) ?></br>
                            <?= $block->escapeHtml(__('City')) ?> : <?= $block->escapeHtml($address->getCity()) ?></br>
                            <?= $block->escapeHtml(__('Country')) ?> : <?= /* @escapeNotVerified */ $block->getCountryByCode($address->getCountryId()) ?></br>
                            <?= $block->escapeHtml(__('State')) ?> : <?= /* @escapeNotVerified */ $address->getRegion()->getRegion() ?></br>
                            <?= $block->escapeHtml(__('Zip/Postal Code')) ?> : <?= $block->escapeHtml($address->getPostcode()) ?></br>
                            <?= $block->escapeHtml(__('Phone')) ?> : <?= $block->escapeHtml($address->getTelephone()) ?></br>
                            <div class="footer-adresse">
                            <a href="<?= $block->escapeUrl($block->getUrl('customer/address/edit', ['id' => $address->getId()])) ?>" class="edit-btn">
                              <i class="fas fa-pen"></i><span><?= $block->escapeHtml(__('Edit')) ?></span>
                            </a>
                            <a class="action delete add-address" href="#" role="delete-address" data-address="<?= $block->escapeHtmlAttr($address->getId()) ?>"><span><?= $block->escapeHtml(__('Delete')) ?></span></a>

                            </div>

                        </address>
                    <?php endforeach; ?>
                </div>
            </div>
            <?php if ($block->getChildHtml('pager')): ?>
                <div class="customer-addresses-toolbar toolbar bottom"><?= $block->getChildHtml('pager') ?></div>
            <?php endif ?>
        <?php else: ?>
            <p class="empty"><?= $block->escapeHtml(__('You have no other address entries in your address book.')) ?></p>
        <?php endif ?>
    </div>
</div>

<!--<div class="actions-toolbar">
    <div class="primary">
        <button type="button" role="add-address" title="<?= $block->escapeHtmlAttr(__('Add New Address')) ?>" class="action primary add"><span><?= $block->escapeHtml(__('Add New Address')) ?></span></button>
    </div>
    <div class="secondary">
        <a class="action back" href="<?= $block->escapeUrl($block->getBackUrl()) ?>"><span><?= $block->escapeHtml(__('Back')) ?></span></a>
    </div>
</div>-->
<script type="text/x-magento-init">
    {
        ".page-main": {
            "address": {
                "deleteAddress": "a[role='delete-address']",
                "deleteUrlPrefix": "<?= $block->escapeJs($block->escapeUrl($block->getDeleteUrl())) ?>id/",
                "addAddress": "button[role='add-address']",
                "addAddressLocation": "<?= $block->escapeJs($block->escapeUrl($block->getAddAddressUrl())) ?>"
            }
        }
    }
</script>
