<?php
// @codingStandardsIgnoreFile
/** @var $block \Magento\Checkout\Block\Cart\Sidebar */

$helperShipping = $this->helper(\Izas\Checkout\Helper\Shipping::class);
?>
<div data-block="minicart" class="minicart-wrapper basket">
    <a class="action showcart link_basket hidden-md-down" href="#"
       data-bind="scope: 'minicart_content'">
        <span data-bind="css: { empty: !!getCartParam('summary_count') == false }, blockLoader: isLoading">
            [
            <!-- ko text: getCartParam('summary_count') --><!-- /ko -->
            ]
        </span>
    </a>
    <?php if ($block->getIsNeedToDisplaySideBar()): ?>
        <div class="block block-minicart"
             data-role="dropdownDialog"
             data-mage-init='{"dropdownDialog":{
                    "appendTo":"[data-block=minicart]",
                    "triggerTarget":".showcart",
                    "timeout": "2000",
                    "closeOnMouseLeave": false,
                    "closeOnEscape": true,
                    "triggerClass":"active",
                    "parentClass":"active",
                    "buttons":[]}}' data-bind="scope: 'minicart_content'">
            <!-- ko if: getCartParam('summary_count') -->
            <span class="text"><?= /* @escapeNotVerified */ __('My Cart'); ?></span>
            <!-- /ko -->
            <div class="basket_items" id="minicart-content-wrapper" data-bind="scope: 'minicart_content'">
                <!-- ko template: getTemplate() --><!-- /ko -->
            </div>
            <!-- ko if: getCartParam('summary_count') -->
            <span class="subtotal"><?= __('Subtotal') ?>:
                <span data-bind="html: getCartParam('subtotal')"></span>
              </span>
            <div class="checkout-link-wrapper">
                <a href="<?= /* @escapeNotVerified */ $block->getShoppingCartUrl() ?>" class="checkout_link"><?= __('Place Order') ?></a>
            </div>
            <div class="free-delivery-alert">
                <img class="image-free-delivery" src="<?= $this->getViewFileUrl('img/icons/icon_delivery.png'); ?>"/>
                <div class="bottom-msg"><?= $helperShipping->getShippingMessage() ?></div>
            </div>
            <!-- /ko -->
            <?= $block->getChildHtml('minicart.addons') ?>
        </div>
    <?php else: ?>
        <script>
            require([
                'jquery'
            ], function ($) {
                $('a.action.showcart').click(function () {
                    $(document.body).trigger('processStart');
                });
            });
        </script>
    <?php endif ?>
    <script>
        window.checkout = <?= /* @escapeNotVerified */ $block->getSerializedConfig() ?>;
    </script>
    <script type="text/x-magento-init">
    {
        "[data-block='minicart']": {
            "Magento_Ui/js/core/app": <?= /* @escapeNotVerified */$block->getJsLayout() ?>
        },
        "*": {
            "Magento_Ui/js/block-loader": "<?= /* @escapeNotVerified */ $block->getViewFileUrl('images/loader-1.gif') ?>"
        }
    }
    </script>
</div>
