# Generated by Django 3.2 on 2023-03-10 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_notifications', '0006_emailnewsnotification_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockemailnotification',
            options={'ordering': ['-created_at'], 'verbose_name': 'Stock email notification', 'verbose_name_plural': 'Stock email notifications'},
        ),
    ]
