<div id="faq-container" class="content_box">
<!--    <div id="faq-search" class="col-md-offset-3 col-md-9 col-xs-12 col-sm-12">-->
<!--        <input type="text" placeholder="--><?php //echo __("Search FAQs") ?><!--"/>-->
<!--    </div>-->
    <section class="cd-faq">
        <?php echo $this->getChildHtml('faq.category') ?>
        <?php echo $this->getChildHtml('faq.faqlist') ?>
        <a href="#0" class="cd-close-panel">Close</a>
    </section> <!-- cd-faq -->
</div>