<!--
/**
* NOTA SOBRE LA LICENCIA DE USO DEL SOFTWARE
* 
* El uso de este software está sujeto a las Condiciones de uso de software que
* se incluyen en el paquete en el documento "Aviso Legal.pdf". También puede
* obtener una copia en la siguiente url:
* http://www.redsys.es/wps/portal/redsys/publica/areadeserviciosweb/descargaDeDocumentacionYEjecutables
* 
* Redsys es titular de todos los derechos de propiedad intelectual e industrial
* del software.
* 
* Quedan expresamente prohibidas la reproducción, la distribución y la
* comunicación pública, incluida su modalidad de puesta a disposición con fines
* distintos a los descritos en las Condiciones de uso.
* 
* Redsys se reserva la posibilidad de ejercer las acciones legales que le
* correspondan para hacer valer sus derechos frente a cualquier infracción de
* los derechos de propiedad intelectual y/o industrial.
* 
* Redsys Servicios de Procesamiento, S.L., CIF B85955367
*/
-->
<img src="https://sis.redsys.es/sis/graficos/botones/pagoBizum.jpg" height="50" width="120"/><br/>



Gracias por confiar en nosotros. En breves segundos será redirigido a la plataforma de pago.<br/>
Si su navegador no le redirecciona automáticamente pulse <a href="javascript:void(0)" onclick="document.bizum_form.submit();">aquí</a> para llevar a cabo el pago.

<form action="<?php echo $this->getEntorno(); ?>" method="post" id="bizum_form" name="bizum_form">
	<input type="hidden" name="Ds_SignatureVersion" value="<?php echo $this->getVersionFirma(); ?>" />
	<input type="hidden" name="Ds_MerchantParameters" value="<?php echo $this->getParametros();  ?>" />
	<input type="hidden" name="Ds_Signature" value="<?php echo $this->getFirma(); ?>" />
</form>
		
<script  type="text/javascript" data-cfasync="false">
	document.bizum_form.submit();
</script>
