<?php

namespace Metagento\Faq\Model\ResourceModel;


class Category extends
    \Magento\Framework\Model\ResourceModel\Db\AbstractDb
{
    public function __construct(
        \Magento\Framework\Model\ResourceModel\Db\Context $context,
        \Magento\UrlRewrite\Model\ResourceModel\UrlRewriteCollectionFactory $urlRewriteCollectionFactory,
        \Metagento\Faq\Model\CategoryFactory $categoryFactory,
        $connectionName = null
    ) {
        $this->_categoryFactory             = $categoryFactory;
        $this->_urlRewriteCollectionFactory = $urlRewriteCollectionFactory;
        parent::__construct($context, $connectionName);
    }

    protected function _construct()
    {
        $this->_init('metagento_faq_category', 'category_id');
    }


    public function saveUrlKey( \Metagento\Faq\Model\Category $category )
    {
        $id       = $category->getId();
        $storeIds = $category->getRealStoreIds();
        $urlKey   = strtolower(str_replace(' ', '-', $category->getData('url_key')));
        foreach ( $storeIds as $storeId ) {
            $urlRewrite = $this->_urlRewriteCollectionFactory->create()
                                                             ->addFieldToFilter('entity_type', 'faq_category')
                                                             ->addFieldToFilter('entity_id', $id)
                                                             ->addFieldToFilter('store_id', $storeId)
                                                             ->getFirstItem();
            $urlRewrite->setData('entity_type', 'faq_category');
            $urlRewrite->setData('entity_id', $id);
            $urlRewrite->setData('request_path', $urlKey);
            $urlRewrite->setData('target_path', 'faq/category/index/id/' . $id);
            $urlRewrite->setData('store_id', $storeId);
            $urlRewrite->setData('is_autogenerated', 0);
            try {
                $urlRewrite->save();
                $this->save($category->setData('url_key', $urlKey));
            } catch ( \Exception $e ) {
                $category->setData('url_key', $urlKey . '-' . $id);
                $this->saveUrlKey($category);
            }
        }
    }

    /**
     * @param \Magento\Framework\Model\AbstractModel $faqCategory
     * @return $this
     */
    public function deleteAllUrlKey( \Magento\Framework\Model\AbstractModel $faqCategory )
    {
        $id = $faqCategory->getId();
        /** @var \Magento\UrlRewrite\Model\ResourceModel\UrlRewriteCollection $urlRewrite */
        $urlRewrite = $this->_urlRewriteCollectionFactory->create();
        $urlRewrite->addFieldToFilter('entity_type', 'faq_category')
                   ->addFieldToFilter('entity_id', $id);
        foreach ( $urlRewrite as $item ) {
            $item->delete();
        }
        return $this;
    }
}