<?php
//@codingStandardsIgnoreFile

/** @var \Mirasvit\Blog\Block\Sidebar\TagCloud $block */
$max = $block->getMaxPopularity() + 1;
?>
              <div class="popular-tag">
                              <span class="title"><?= /* @escapeNotVerified */ __('POPULAR TAGS') ?></span>
                              <ul class="popular-taf-items">
        <?php foreach ($block->getCollection() as $tag): ?>
          <li>
            <a href="<?= $tag->getUrl() ?>" style="">
                <?= $tag->getName() ?>
            </a>
          </li>
        <?php endforeach ?>
                            </ul>
                        </div>
