<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var  $block \Magento\Sales\Block\Order\Item\Renderer\DefaultRenderer */
$_item = $block->getItem();

$productOptions = $_item->getProductOptions();
?>
<div class="order-item-detail">
  <?php
  $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
  $productHelper = $objectManager->get('Magento\Catalog\Helper\Product');
  $product = $objectManager->get('Magento\Catalog\Model\Product')->loadByAttribute('sku',$_item->getData('sku'));
  $imagehelper = $objectManager->get('Magento\Catalog\Helper\Image')->init($product, 'product_page_image_small')->resize(300)->getUrl();

          ?>
          <img class="order-item-img"
                src="<?php echo $productHelper->getSmallImageUrl($product); ?>"
                width="154px"/>
<div class="order-item-infos">
  <a href="#" class="order-item-title"><?php echo $_item->getName(); ?></a>
  <span><?= /* @escapeNotVerified */  __('SIZE') ?>: <?php echo $productOptions['attributes_info'][0]['value']; ?></span>
  <span><?= /* @escapeNotVerified */  __('QTY') ?>: <?php echo $productOptions['info_buyRequest']['qty']; ?></span>
  <span><?php echo $_item->getPrice(); ?></span>
</div>
</div>
<span class="order-line"></span>
<!--
<div class="order_item" id="order-item-row-<?= /* @escapeNotVerified */ $_item->getId() ?>">
  <div class="order_item_level">
    <div class="order_level active">
        <strong class="product name product-item-name"><?= $block->escapeHtml($_item->getName()) ?></strong>
        <?php if ($_options = $block->getItemOptions()): ?>
        <dl class="item-options">
        <?php foreach ($_options as $_option) : ?>
            <dt><?= $block->escapeHtml($_option['label']) ?></dt>
            <?php if (!$block->getPrintStatus()): ?>
                <?php $_formatedOptionValue = $block->getFormatedOptionValue($_option) ?>
                <dd>
                    <?php if (isset($_formatedOptionValue['full_view'])): ?>
                        <?= $block->escapeHtml($_formatedOptionValue['full_view'], ['a']) ?>
                    <?php else: ?>
                        <?=$block->escapeHtml($_formatedOptionValue['value'], ['a']) ?>
                    <?php endif; ?>
                </dd>
            <?php else: ?>
                <dd>
                    <?= nl2br($block->escapeHtml((isset($_option['print_value']) ? $_option['print_value'] : $_option['value']))) ?>
                </dd>
            <?php endif; ?>
        <?php endforeach; ?>
        </dl>
        <?php endif; ?>
        <?php $addtInfoBlock = $block->getProductAdditionalInformationBlock(); ?>
        <?php if ($addtInfoBlock) :?>
            <?= $addtInfoBlock->setItem($_item)->toHtml() ?>
        <?php endif; ?>
        <?= $block->escapeHtml($_item->getDescription()) ?>
    </div>
    <div class="order_level active"><?= /* @escapeNotVerified */ $block->prepareSku($block->getSku()) ?></div>
    <div class="order_level active">
        <?= $block->getItemPriceHtml() ?>
    </div>
    <div class="order_level active">
        <ul class="items-qty">
        <?php if ($block->getItem()->getQtyOrdered() > 0): ?>
            <li class="item">
                <span class="title"><?= /* @escapeNotVerified */ __('Ordered') ?></span>
                <span class="content"><?= /* @escapeNotVerified */ $block->getItem()->getQtyOrdered()*1 ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyShipped() > 0): ?>
            <li class="item">
                <span class="title"><?= /* @escapeNotVerified */ __('Shipped') ?></span>
                <span class="content"><?= /* @escapeNotVerified */ $block->getItem()->getQtyShipped()*1 ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyCanceled() > 0): ?>
            <li class="item">
                <span class="title"><?= /* @escapeNotVerified */ __('Canceled') ?></span>
                <span class="content"><?= /* @escapeNotVerified */ $block->getItem()->getQtyCanceled()*1 ?></span>
            </li>
        <?php endif; ?>
        <?php if ($block->getItem()->getQtyRefunded() > 0): ?>
            <li class="item">
                <span class="title"><?= /* @escapeNotVerified */ __('Refunded') ?></span>
                <span class="content"><?= /* @escapeNotVerified */ $block->getItem()->getQtyRefunded()*1 ?></span>
            </li>
        <?php endif; ?>
        </ul>
    </div>
    <div class="order_level active">
        <?= $block->getItemRowTotalHtml() ?>
    </div>
  </div>
</div>-->
