# Generated by Django 4.2.3 on 2023-07-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productinventory',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='productinventory',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
