<?php
/* @var $block \WebPanda\Rma\Block\Customer\Rma\ListRma */
?>

<button id="new-rma-button" type="button" class="action primary" title="<?php echo __('Create New Return') ?>" style="display:none;">
    <span><?php echo __('Create New Return') ?></span>
</button>
<div class="clearfix"></div>
<script>
    require(['jquery'], function($) {
        $(document).ready(function() {
            $('#new-rma-button').on('click', function() {
                $(location).attr('href', <?php echo \Zend_Json::encode($block->getUrl('*/*/create')); ?>);
            });
        });
    });
</script>
<?php
$rmas = $block->getRmaCollection();
$helper = $this->helper('\WebPanda\Rma\Helper\Data');
if ($rmas && count($rmas)):
    ?>
    <div class="table-wrapper my-rma-list">
        <table class="data table my-rma-items history" id="my-rma-table">
            <caption class="table-caption"><?php echo __('My Returns') ?></caption>
            <thead>
                <tr>
                    <th scope="col" class="table-col id"><?php echo __('Return ID #') ?></th>
                    <th scope="col" class="table-col order_id"><?php echo __('Order ID #') ?></th>
                    <th scope="col" class="table-col products"><?php echo __('Product(s)') ?></th>
                    <th scope="col" class="table-col status"><?php echo __('Status') ?></th>
                    <th scope="col" class="table-col updated_at"><?php echo __('Updated At') ?></th>
                    <th scope="col" class="table-col created_at"><?php echo __('Created At') ?></th>
                    <th scope="col" class="table-col actions">&nbsp;</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach ($rmas as $rma): ?>
                    <tr>
                        <td data-th="<?php echo $block->escapeHtml(__('Return ID #')) ?>" class="table-col id">
                            <?php echo $rma->getIncrementId() ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Order ID #')) ?>" class="table-col order_id">
                            <a href="<?php echo $block->getOrderUrl($rma->getOrderId()) ?>">
                                <span><?php echo $rma->getOrderIncrementId() ?></span>
                            </a>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Products')) ?>" class="table-col products">
                            <?php foreach($rma->getItemsCollection() as $rmaItem): ?>
                                <?php if ($block->getProductExists($rmaItem->getProductId())): ?>
                                    <a href="<?php echo $block->getProductUrl($rmaItem) ?>">
                                        <span><?php echo $rmaItem->getName() ?></span>
                                    </a>
                                <?php else: ?>
                                    <?php echo $rmaItem->getName() ?>
                                <?php endif; ?>
                                <br/>
                            <?php endforeach; ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Status')) ?>" class="table-col status">
                            <?php echo $helper->getStatusHtml($rma) ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Updated At')) ?>" class="table-col updated_at">
                            <?php echo $block->formatDate($rma->getUpdatedAt()) ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Created At')) ?>" class="table-col created_at">
                            <?php echo $block->formatDate($rma->getCreatedAt()) ?>
                        </td>
                        <td data-th="<?php echo $block->escapeHtml(__('Actions')) ?>" class="table-col actions">
                            <a href="<?php echo $block->getRequestUrl($rma->getId()) ?>">
                                <span><?php echo __('View Return') ?></span>
                            </a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
    </div>
<?php else: ?>
    <div class="rma-message message info empty"><span><?php echo __('You have no returns.'); ?></span></div>
<?php endif ?>
