<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 *
 * @var $block \Magento\Customer\Block\Account\Forgotpassword
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Account\Forgotpassword $block */
?>
<section class="" id="product_detail">
      <div class="container">
        <div class="content_box">
<div class="space_80"></div>
<form class="form_signin form password forget"
      action="<?= $block->escapeUrl($block->getUrl('*/*/forgotpasswordpost')) ?>"
      method="post"
      id="form-validate"
      data-mage-init='{"validation":{}}'>
      <div class="col-6 ml-auto mr-auto">
              <h1 class="title_form"><?= $block->escapeHtml(__('Forgot Your Password?')) ?></h1>
              <p class="description_content">
                <?= $block->escapeHtml(__('Please enter your email address below to receive a password reset link.')) ?>
              </p>
    <div class="fieldset" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">
        <div class="field email required">
            <div class="control">
                <input type="email" placeholder="<?= $block->escapeHtml(__('Email')) ?>" name="email" alt="email" id="email_address" class="form-control" value="<?= $block->escapeHtmlAttr($block->getEmailValue()) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <?= $block->getChildHtml('form_additional_info') ?>
    </div>
    <div class="actions-toolbar">
        <div class="primary">
            <button type="submit" class="submit-payement action submit primary"><span><?= $block->escapeHtml(__('Reset My Password')) ?></span></button>
        </div>
    </div>
  </div>
</form>
<div class="space_80"></div>
</div>
</div>
</section>
