<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Login $block */
?>


        <form  class="form_signin form form-login"
              action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>"
              method="post"
              id="login-form"
              data-mage-init='{"validation":{}}'>
            <?= $block->getBlockHtml('formkey') ?>
            <div class="" data-hasrequired="<?= $block->escapeHtml(__('* Required Fields')) ?>">
                <h3 class="title-tab"><?php echo __('SIGN IN WITH YOUR EMAIL ADDRESS') ?></h3>
                <div class="form-group field email required">

                        <input placeholder="<?= $block->escapeHtml(__('Email')) ?>" name="login[username]" value="<?= $block->escapeHtmlAttr($block->getUsername()) ?>" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> id="email" type="email" class="form-control" title="<?= $block->escapeHtmlAttr(__('Email')) ?>" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">

                </div>
                <div class="form-group field password required">

                        <input placeholder="<?= $block->escapeHtml(__('Password')) ?>" name="login[password]" type="password" <?php if ($block->isAutocompleteDisabled()): ?> autocomplete="off"<?php endif; ?> class="form-control" id="pass" title="<?= $block->escapeHtmlAttr(__('Password')) ?>" data-validate="{required:true}">

                </div>
               
                <?= $block->getChildHtml('form_additional_info') ?>
                  <button type="submit" class="submit-payement action login primary" name="send" id="send2"><span><?= $block->escapeHtml(__('Sign In')) ?></span></button>
                  
                  <a class="forgot-password action remind" href="<?= $block->escapeUrl($block->getForgotPasswordUrl()) ?>"><span><?= $block->escapeHtml(__('Forgot Your Password?')) ?></span></a>
                  <?php if(isset($_GET['origin'])){ ?>
                        <?php __('If don\'t have an account yet,') ?><a class="forgot-password action remind" href="<?= $block->getUrl('customer/account'); ?>"><span><?= $block->escapeHtml(__('Hazte Cliente')) ?></span></a>
                <?php } ?>
                  <!--<span class="line-or"><span><?php echo __('OR') ?></span></span>
                  <h3 class="title-tab"><?php echo __('SIGN IN WITH') ?>...</h3>
                  <?php //$block->getChildHtml('social-login') ?>-->

            </div>
        </form>
<style>
.social-login-authentication-channel{
  display:none;
}
.remember-me-box{
    display: flex !important;
}
</style>
