<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Form\Register $block */
?>

<?= $block->getChildHtml('form_fields_before') ?>
<?php /* Extensions placeholder */ ?>
<?= $block->getChildHtml('customer.form.register.extra') ?>
<script src="https://challenges.cloudflare.com/turnstile/v0/api.js" async defer></script>
<form class="form create account form-create-account" action="<?= $block->escapeUrl($block->getPostActionUrl()) ?>" method="post" id="form-validate" enctype="multipart/form-data" autocomplete="off">
    <?= /* @noEscape */ $block->getBlockHtml('formkey'); ?>
    <!--<h3 class="title-tab"><?php echo __('SIGN UP WITH') ?>...</h3>


  <div class="rs-signup">
                <?= $block->getChildHtml('social-register') ?>
              </div>
              <p class="description-signup">
                <?php echo __('Signing up with you social is super quick. No need to remember extra passwords')?>.
                <?php echo __('We’d never share any of your data or post anything on your account')?>.
              </p>
            <span class="line-or"><span><?php echo __('OR') ?></span></span>-->
            <h3 class="title-tab"><?php echo __('SIGN UP WITH YOUR EMAIL ADDRESS') ?></h3>
    <div class="fieldset create info">
        <input type="hidden" name="success_url" value="<?= $block->escapeUrl($block->getSuccessUrl()) ?>">
        <input type="hidden" name="error_url" value="<?= $block->escapeUrl($block->getErrorUrl()) ?>">
        <?= $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Name')->setObject($block->getFormData())->setForceUseCustomerAttributes(true)->toHtml() ?>
        <div class="form-group field required">
            <div class="control">
                <input type="email" name="email" autocomplete="email" id="email_address" value="<?= $block->escapeHtmlAttr($block->getFormData()->getEmail()) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Email')) ?>" class="form-control" data-mage-init='{"mage/trim-input":{}}' data-validate="{required:true, 'validate-email':true}">
            </div>
        </div>
        <div class="form-group create account" data-hasrequired="<?= $block->escapeHtmlAttr(__('* Required Fields')) ?>">

            <div class="form-group field password required">
                <div class="control">
                    <input type="password" name="password" id="password"
                           placeholder="<?= $block->escapeHtmlAttr(__('Password')) ?>"
                           class="form-control"
                           data-password-min-length="<?= $block->escapeHtmlAttr($block->getMinimumPasswordLength()) ?>"
                           data-password-min-character-sets="<?= $block->escapeHtmlAttr($block->getRequiredCharacterClassesNumber()) ?>"
                           data-validate="{required:true, 'validate-customer-password':true}"
                           autocomplete="off">
                    <!--<div id="password-strength-meter-container" data-role="password-strength-meter" aria-live="polite">
                        <div id="password-strength-meter" class="password-strength-meter password_difficulty">
                            <?= $block->escapeHtml(__('Password Strength')) ?>:
                            <span id="password-strength-meter-label" class="pd_level" data-role="password-strength-meter-label">
                                <?= $block->escapeHtml(__('No Password')) ?>
                            </span>
                        </div>
                    </div>-->
                </div>

            </div>
            <div class="field required">
                <div class="control">
                    <input type="password" name="password_confirmation" placeholder="<?= $block->escapeHtmlAttr(__('Confirm Password')) ?>" id="password-confirmation" class="form-control" data-validate="{required:true, equalTo:'#password'}" autocomplete="off">
                </div>
            </div>

            <?= $block->getChildHtml('form_additional_info') ?>
        </div>

        <?php $_dob = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Dob') ?>
        <?php if ($_dob->isEnabled()): ?>
            <?= $_dob->setDate($block->getFormData()->getDob())->toHtml() ?>
        <?php endif ?>

        <?php $_taxvat = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Taxvat') ?>
        <?php if ($_taxvat->isEnabled()): ?>
            <?= $_taxvat->setTaxvat($block->getFormData()->getTaxvat())->toHtml() ?>
        <?php endif ?>

        <?php $_gender = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Gender') ?>
        <?php if ($_gender->isEnabled()): ?>
            <?= $_gender->setGender($block->getFormData()->getGender())->toHtml() ?>
        <?php endif ?>
    </div>
    <?php if ($block->getShowAddressFields()): ?>
        <div class="fieldset address">
            <input type="hidden" name="create_address" value="1" />

            <?php $_company = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Company') ?>
            <?php if ($_company->isEnabled()): ?>
                <?= $_company->setCompany($block->getFormData()->getCompany())->toHtml() ?>
            <?php endif ?>

            <?php $_telephone = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Telephone') ?>
            <?php if ($_telephone->isEnabled()): ?>
                <?= $_telephone->setTelephone($block->getFormData()->getTelephone())->toHtml() ?>
            <?php endif ?>

            <?php $_fax = $block->getLayout()->createBlock('Magento\Customer\Block\Widget\Fax') ?>
            <?php if ($_fax->isEnabled()): ?>
                <?= $_fax->setFax($block->getFormData()->getFax())->toHtml() ?>
            <?php endif ?>

            <?php $_streetValidationClass = $this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('street'); ?>

            <div class="field street required">
                <label for="street_1" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?></span></label>
                <div class="control">
                    <input type="text" name="street[]" value="<?= $block->escapeHtmlAttr($block->getFormData()->getStreet(0)) ?>" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('street') ?>" id="street_1" class="form-control <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                    <div class="nested">
                        <?php $_streetValidationClass = trim(str_replace('required-entry', '', $_streetValidationClass)); ?>
                        <?php for ($_i = 2, $_n = $this->helper('Magento\Customer\Helper\Address')->getStreetLines(); $_i <= $_n; $_i++): ?>
                            <div class="field additional form-group">
                                <div class="control">
                                    <input type="text" name="street[]" value="<?= $block->escapeHtml($block->getFormData()->getStreetLine($_i - 1)) ?>" placeholder="<?= $block->escapeHtmlAttr(__('Street Address %1', $_i)) ?>" id="street_<?= /* @noEscape */ $_i ?>" class="form-control <?= $block->escapeHtmlAttr($_streetValidationClass) ?>">
                                </div>
                            </div>
                        <?php endfor; ?>
                    </div>
                </div>
            </div>

            <div class="field required">
                <label for="city" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?></span></label>
                <div class="control">
                    <input type="text" name="city" value="<?= $block->escapeHtmlAttr($block->getFormData()->getCity()) ?>" placeholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('city') ?>" class="form-control <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('city')) ?>" id="city">
                </div>
            </div>

            <div class="field region required">
                <label for="region_id" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?></span></label>
                <div class="control">
                    <select id="region_id" name="region_id" title="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="validate-select" style="display:none;">
                        <option value=""><?= $block->escapeHtml(__('Please select a region, state or province.')) ?></option>
                    </select>
                    <input type="text" id="region" name="region" value="<?= $block->escapeHtml($block->getRegion()) ?>" placeholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('region') ?>" class="form-control <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('region')) ?>" style="display:none;">
                </div>
            </div>

            <div class="field zip required">
                <label for="zip" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?></span></label>
                <div class="control">
                    <input type="text" name="postcode" value="<?= $block->escapeHtmlAttr($block->getFormData()->getPostcode()) ?>" placeholder="<?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('postcode') ?>" id="zip" class="form-control validate-zip-international <?= $block->escapeHtmlAttr($this->helper('Magento\Customer\Helper\Address')->getAttributeValidationClass('postcode')) ?>">
                </div>
            </div>

            <div class="field country required">
                <label for="country" class="label"><span><?= /* @noEscape */ $block->getAttributeData()->getFrontendLabel('country_id') ?></span></label>
                <div class="control">
                    <?= $block->getCountryHtmlSelect() ?>
                </div>
            </div>
            <?php $addressAttributes = $block->getChildBlock('customer_form_address_user_attributes');?>
            <?php if ($addressAttributes): ?>
                <?php $addressAttributes->setEntityType('customer_address'); ?>
                <?php $addressAttributes->setFieldIdFormat('address:%1$s')->setFieldNameFormat('address[%1$s]');?>
                <?php $block->restoreSessionData($addressAttributes->getMetadataForm(), 'address');?>
                <?= $addressAttributes->setShowContainer(false)->toHtml() ?>
            <?php endif;?>
            <input type="hidden" name="default_billing" value="1">
            <input type="hidden" name="default_shipping" value="1">
        </div>

    <?php endif; ?>

    <div class="preferences">
      <h3 class="title-tab"><?php echo __('CONTACT PREFERENCES') ?></h3>
      <p><?php echo __('Tell us what emails you’d like') ?></p>

      <ul class="ul-radio">

                <li>
                  <div class="radio_line">
                  <input  id="activewear" type="checkbox" name="activewear" class="radio">

                  <label for="activewear" class="">
                    <span class="radio_check"><i class="fas fa-circle"></i></span>
                    <?php echo __('Activewear') ?>
                  </label>
                </div>
                </li>
                <li>
                  <div class="radio_line">
                  <input  id="rainwear" type="checkbox" name="rainwear" class="radio">

                  <label for="rainwear" class="">
                    <span class="radio_check"><i class="fas fa-circle"></i></span>
                    <?php echo __('Rainwear') ?>
                  </label>
                </div>
                </li>
                <li>
                  <div class="radio_line">
                  <input  id="lifestyle" type="checkbox" name="lifestyle" class="radio">

                  <label for="lifestyle" class="">
                    <span class="radio_check"><i class="fas fa-circle"></i></span>
                  <?php echo __('Lifestyle') ?>
                  </label>
                </div>
                </li>
                <li>
                  <div class="radio_line">
                  <input  id="climbing" type="checkbox" name="climbing" class="radio">

                  <label for="climbing" class="">
                    <span class="radio_check"><i class="fas fa-circle"></i></span>
                    <?php echo __('Climbing') ?>
                  </label>
                </div>
                </li>
                <li>
                  <div class="radio_line">
                  <input  id="skiwear" type="checkbox" name="skiwear" class="radio">

                  <label for="skiwear" class="">
                    <span class="radio_check"><i class="fas fa-circle"></i></span>
                    <?php echo __('Skiwear') ?>
                  </label>
                </div>
                </li>
                <li>
                  <div class="radio_line">
                  <input  id="kids" type="checkbox" name="kids" class="radio">

                  <label for="kids" class="">
                    <span class="radio_check"><i class="fas fa-circle"></i></span>
                    <?php echo __('Ropa niño') ?>
                  </label>
                </div>
                </li>
              </ul>
      <p class="p-description">
          <?= $block->getChildHtml('izas.data.protection.register.form') ?>
      </p>
    </div>
    <div class="field terms-and-condition required">
        <div class="control">
            <input type="checkbox" id="privacity" name="privacity" data-validate="{required:true}" class="input-checkbox checkbox required" value="1">
            <label for="privacity" class="label">
                <?= __('I have read the')?>
                <a href="<?= $block->getUrl("privacy-policy-cookie-restriction-mode") ?>" target="_blank"><?= __('Privacy Policy')?></a>
                <?= __('and I accept the')?>
                <a href="<?= $block->getUrl("aviso-legal") ?>" target="_blank"><?= __('Terms and Conditions')?></a>
                <?= __('from service')?>
            </label>
            <div class="clear"></div>
            <?= $block->getChildHtml('custom-news.checkbox') ?>
        </div>
    </div>
    <div class="center checkbox mb-3">
                        <!-- The following line controls and configures the Turnstile widget. -->
                        <div class="cf-turnstile" data-sitekey="0x4AAAAAAAChPM_XijmD2CI5" data-theme="light"></div>
                        <!-- end. -->
                    </div>
        <div class="submit_form">
            <button type="submit" class="submit-payement action submit primary" title="<?= $block->escapeHtmlAttr(__('Create an Account')) ?>"><span><?= $block->escapeHtml(__('JOIN IZAS')) ?></span></button>
        </div>
</form>

<script>
require([
    'jquery',
    'mage/mage'
], function($){

    var dataForm = $('#form-validate');
    var ignore = <?= /* @noEscape */ $_dob->isEnabled() ? '\'input[id$="full"]\'' : 'null' ?>;

    dataForm.mage('validation', {
    <?php if ($_dob->isEnabled()): ?>
        errorPlacement: function(error, element) {
            if (element.prop('id').search('full') !== -1) {
                var dobElement = $(element).parents('.customer-dob'),
                    errorClass = error.prop('class');
                error.insertAfter(element.parent());
                dobElement.find('.validate-custom').addClass(errorClass)
                    .after('<div class="' + errorClass + '"></div>');
            }
            else {
                error.insertAfter(element);
            }
        },
        ignore: ':hidden:not(' + ignore + ')'
    <?php else: ?>
        ignore: ignore ? ':hidden:not(' + ignore + ')' : ':hidden'
    <?php endif ?>
    }).find('input:text').attr('autocomplete', 'off');

});
</script>
<?php if ($block->getShowAddressFields()): ?>
<script type="text/x-magento-init">
    {
        "#country": {
            "regionUpdater": {
                "optionalRegionAllowed": <?= /* @noEscape */ $block->getConfig('general/region/display_all') ? 'true' : 'false' ?>,
                "regionListId": "#region_id",
                "regionInputId": "#region",
                "postcodeId": "#zip",
                "form": "#form-validate",
                "regionJson": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getRegionJson() ?>,
                "defaultRegion": "<?= (int) $block->getFormData()->getRegionId() ?>",
                "countriesWithOptionalZip": <?= /* @noEscape */ $this->helper(\Magento\Directory\Helper\Data::class)->getCountriesWithOptionalZip(true) ?>
            }
        }
    }
</script>
<?php endif; ?>

<script type="text/x-magento-init">
    {
        ".field.password": {
            "passwordStrengthIndicator": {
                "formSelector": "form.form-create-account"
            }
        }
    }
</script>
