<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

// @codingStandardsIgnoreFile

/** @var \Magento\Customer\Block\Widget\Fax $block */
?>

<div class="field form-group fax <?= $block->isRequired() ? 'required' : '' ?>">

    <div class="control">
        <?php
            $_validationClass = $block->escapeHtmlAttr(
                $this->helper('Magento\Customer\Helper\Address')
                     ->getAttributeValidationClass('fax')
            );
        ?>
        <input type="text"
               name="fax"
               id="fax"
               value="<?= $block->escapeHtmlAttr($block->getFax()) ?>"
               placeholder="<?= $block->escapeHtmlAttr(__('Fax')) ?>"
               class="form-control <?= $_validationClass ?: '' ?>"
        >
    </div>
</div>
