<section id="checkout-page">
    <div class="container">
        <div class="content_box">
            <div class="col-md-6 mx-auto">
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist">

                        <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab"
                           role="tab"><?php echo __('NEW TO IZAS') ?>?</a>
                        <a class="nav-item nav-link " id="nav-profile-tab" data-toggle="tab"
                           role="tab"><?php echo __('ALREADY REGISTERED') ?>?</a>
                    </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                    <div class="tab-pane fade active show" id="nav-home" role="tabpanel">
                        <?php echo $block->getChildHtml('customer_form_register'); ?>
                    </div>
                    <div class="tab-pane fade" id="nav-profile" role="tabpanel">
                        <?php echo $block->getChildHtml('customer.login.container'); ?>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</section>
<script type="text/x-magento-init">
{
    "*": {
        "IzasCustomer": {}
    }

}
</script>
