<section id="checkout-page">
    <div class="container">
        <div class="content_box">
            <div class="col-md-8 mx-auto">
                <nav>
                    <div class="nav nav-tabs" id="nav-tab" role="tablist" >
                        <?php if(isset($_GET['origin'])){ ?>
                            <a class="nav-item nav-link active" id="nav-home-tab" data-toggle="tab" style="cursor:pointer;"
                            role="tab"><?php echo __('GUEST') ?></a>
                            <a class="nav-item nav-link" id="nav-profile-tab" data-toggle="tab" style="cursor:pointer;"
                           role="tab"><?php echo __('ALREADY REGISTERED') ?>?</a>
                        <?php }else{ ?>
                            <a class="nav-item nav-link" id="nav-home-tab" data-toggle="tab" style="cursor:pointer;"
                           role="tab"><?php echo __('NEW TO IZAS') ?>?</a>
                           <a class="nav-item nav-link active" id="nav-profile-tab" data-toggle="tab" style="cursor:pointer;"
                           role="tab"><?php echo __('ALREADY REGISTERED') ?>?</a>
                        <?php } ?>
                            
                    </div>
                </nav>
                <div class="tab-content" id="nav-tabContent">
                    <?php if(isset($_GET['origin'])){ ?>
                        <div class="tab-pane fade  active show" id="nav-home" role="tabpanel">
                            <?php echo $block->getChildHtml('customer_form_guest'); ?>
                        </div>
                        <div class="tab-pane fade" id="nav-profile" role="tabpanel">
                        <?php echo $block->getChildHtml('customer.login.container'); ?>
                    </div>
                        
                    <?php }else{ ?>
                        <div class="tab-pane fade" id="nav-home" role="tabpanel">
                            <?php echo $block->getChildHtml('customer_form_register'); ?>
                        </div>
                        <div class="tab-pane fade  active show" id="nav-profile" role="tabpanel">
                        <?php echo $block->getChildHtml('customer.login.container'); ?>
                    </div>
                    <?php } ?>
                    
                </div>
                <style>
                    .nav-link{
                        cursor:pointer;
                    }
                    a.nav-link:not(.active) {
                        font-weight: 300;
                        font-size: 12px;
                    }
                </style>
            </div>
        </div>
    </div>
    </div>
</section>
<script type="text/x-magento-init">
{
    "*": {
        "IzasCustomer": {}
    }

}
</script>
