<?php
// @codingStandardsIgnoreFile
?>
<?php
/**
 * Category layered navigation state
 *
 * @var $block \WeltPixel\LayeredNavigation\Block\Navigation\State
 */
?>
<?php $_filters = $block->getActiveFilters() ?>
<?php if (!empty($_filters)): ?>
  <div class="shopping_by">

      <ul class="options_selected">
        <?php foreach ($_filters as $_filter): ?>

        <?php
            $requestVar = $_filter->getFilter()->getRequestVar();
            $filterItemVal =  (is_array($_filter->getValue())) ? implode('-', $_filter->getValue()) : $_filter->getValue();
            $dataAttrId = ($requestVar != 'cat') ? $_filter->getFilter()->getAttributeModel()->getAttributeId() . '_' . $filterItemVal : '0_'.$filterItemVal;
            ?>
            <li class="option_selected"  data-attr-id="<?= /* @escapeNotVerified */ $dataAttrId ?>">

                <?php
                $clearLinkUrl = $_filter->getClearLinkUrl();
                $currentFilterName = $block->escapeHtml(__($_filter->getName())) . " " . $block->stripTags($_filter->getLabel());
                if ($clearLinkUrl):
                    ?>
                    <a class="action previous" href="<?= /* @escapeNotVerified */ $_filter->getRemoveUrl() ?>"
                       title="<?= /* @escapeNotVerified */ __('Previous') ?>">
                        <span><?= /* @escapeNotVerified */ __('Previous') ?></span>
                    </a>
                    <a class="action remove"
                       title="<?= $block->escapeHtml($_filter->getFilter()->getClearLinkText()) ?>"
                       href="<?= /* @escapeNotVerified */ $clearLinkUrl ?>">
                        <i class="fas fa-times"></i>
                    </a>
                <?php else: ?>
                    <a class="action remove" href="<?= /* @escapeNotVerified */ $_filter->getRemoveUrl() ?>"
                       title="<?= /* @escapeNotVerified */ $block->escapeHtml(__('Remove')) . " " . $currentFilterName ?>">
                        <i class="fas fa-times"></i>
                    </a>
                <?php endif; ?>
                <span class="min_title_option"><?= $block->escapeHtml(__($_filter->getName())) ?>:</span>
                <span class="value_min_option"><?= /* @escapeNotVerified */ $block->stripTags($_filter->getLabel()) ?></span>
            </li>
        <?php endforeach; ?>
    </ul>
      <?php if ($block->getLayer()->getState()->getFilters()): ?>
          <a href="<?= /* @escapeNotVerified */ $block->getClearUrl() ?>" class="close_all_options"><?= /* @escapeNotVerified */ __('CLEAR ALL') ?></a>

      <?php endif; ?>
</div>
<?php endif; ?>
<script type="text/x-magento-init">
{
    "*": {
        "IzasFilters": {}
    }

}
</script>
