<div id="faq-container"  class="content_box">
<!--    <div id="faq-search" class="col-md-offset-3 col-md-8 col-xs-12 col-sm-12">-->
<!--        <input id="faq-search-content" class="form-control" type="text" placeholder="--><?php //echo __("Search FAQs") ?><!--"/>-->
<!--        <button id="faq-search-button" type="button" class="button">--><?php //echo __("Search") ?><!--</button>-->
<!--    </div>-->
    <?php echo $this->getChildHtml('faq.category') ?>
    <?php echo $this->getChildHtml('faq.faqlist') ?>
</div>
