<?php
/* @var $block \WebPanda\Rma\Block\Adminhtml\Rma\Edit\Tab\Products */
?>
<?php
$blockGrid = $block->getBlockGrid();
$gridJsObjectName = $blockGrid->getJsObjectName();
?>
<?php  echo $block->getGridHtml(); ?>
<input type="hidden" name="assigned_items" id="in_assigned_items" data-form-part="rma_rma_form" value="" />
<script type="text/x-magento-init">
    {
        "*": {
            "WebPanda_Rma/js/rma/edit/assigned-items": {
                "selectedItems": <?php /* @escapeNotVerified */ echo $block->getItemsJson(); ?>,
                "gridJsObjectName": <?php /* @escapeNotVerified */ echo '"' . $gridJsObjectName . '"' ?: '{}'; ?>
            }
        }
    }
</script>
<!-- @todo remove when "UI components" will support such initialization -->
<script>
    //require('mage/apply/main').apply();
</script>
