<?php
/**
 * Product list template
 *
 * @var $block \Izas\Catalog\Block\Cms\Category\Product\ListProduct
 */
?>
<?php
    // @codingStandardsIgnoreFile
    $products = $block->getTopSellingProducts();
?>
<?php if (!$products->count()): ?>
    <div class="message info empty"><div><?= /* @escapeNotVerified */ __('We can\'t find products matching the selection.') ?></div></div>
<?php else: ?>
    <div class="container topseller-product-list">
        <div class="products wrapper product-list">
            <ol class="products list items product-items row">
                <?php /** @var $_product \Magento\Catalog\Model\Product */ ?>
                <?php foreach ($products as $_product): ?>
                    <li class="item product product-item col-12 col-md-6 col-lg-4">
                        <?php echo $block->getProductRenderHtml($_product) ?>
                    </li>
                <?php endforeach; ?>
            </ol>
        </div>
    </div>
<?php endif; ?>