<?php
// @codingStandardsIgnoreFile
$helperShipping = $this->helper(\Izas\Checkout\Helper\Shipping::class);
?>
<?php $_order = $block->getOrder() ?>
<?php if ($_order): ?>
<?php $_items = $_order->getAllItems(); ?>

<?php foreach ($_items as $_item): ?>
<?php if (!$_item->getParentItem()) : ?>
<tbody>
    <?= $block->getItemHtml($_item) ?>
</tbody>
<?php endif; ?>
<?php endforeach; ?>
<?= $block->getChildHtml('order_totals') ?>



 <h1 style="text-align:center;">
          <span style="font-size:16px">
            <?php //echo __('WE EXPECT TO DELIVER YOUR ITEMS ON') ?>
          </span>
        </h1>
<p style="text-align:center;font-weight:400;font-size:15px;">
    <?php $helperShipping->getShippingMessage()?>
</p>
<?php endif; ?>