<?php
// @codingStandardsIgnoreFile
/** @var \Magento\ConfigurableProduct\Pricing\Render\FinalPriceBox $block */

/** @var \Magento\Framework\Pricing\Price\PriceInterface $priceModel */
$priceModel = $block->getPriceType('regular_price');

/** @var \Magento\Framework\Pricing\Price\PriceInterface $finalPriceModel */
$finalPriceModel = $block->getPriceType('final_price');
$idSuffix = $block->getIdSuffix() ? $block->getIdSuffix() : '';
$schema = ($block->getZone() == 'item_view') ? true : false;
?>
<?php if ($block->hasSpecialPrice()): ?>
    <span class="special-price">
        <?php /* @escapeNotVerified */
        echo str_replace(",00", "", $block->renderAmount($finalPriceModel->getAmount(), [
            'display_label' => __(''),
            'price_id' => $block->getPriceId('product-price-' . $idSuffix),
            'price_type' => 'finalPrice',
            'include_container' => true,
            'schema' => $schema
        ])); ?>
    </span>
    <span class="old-price sly-old-price no-display">
        <?php /* @escapeNotVerified */
        echo $block->renderAmount($priceModel->getAmount(), [
            'display_label' => '',
            'price_id' => $block->getPriceId('old-price-' . $idSuffix),
            'price_type' => 'oldPrice',
            'include_container' => true,
            'skip_adjustments' => true
        ]); ?>
    </span>
<?php else: ?>
    <span class="normal-price">
    <?php /* @escapeNotVerified */
    echo str_replace(",00", "", $block->renderAmount($finalPriceModel->getAmount(), [
        'price_id' => $block->getPriceId('product-price-' . $idSuffix),
        'price_type' => 'finalPrice',
        'include_container' => true,
        'schema' => $schema
    ])); ?>
</span>
<?php endif; ?>

<?php if ($block->showMinimalPrice()): ?>
    <?php if ($block->getUseLinkForAsLowAs()): ?>
        <a href="<?= /* @escapeNotVerified */
        $block->getSaleableItem()->getProductUrl() ?>" class="minimal-price-link">
            <?= /* @escapeNotVerified */
            $block->renderAmountMinimal() ?>
        </a>
    <?php else: ?>
        <span class="minimal-price-link">
            <?= /* @escapeNotVerified */
            $block->renderAmountMinimal() ?>
        </span>
    <?php endif ?>
<?php endif; ?>
