name: 02/ PROD - FULL
on:
    workflow_dispatch:
        inputs:
            logLevel:
                description: 'Log level'
                required: true
                default: 'warning'
            tags:
                description: 'Test scenario tags'
jobs:
    deploy:
        name: 02/ PROD - FULL
        runs-on: ubuntu-latest
        steps:
            -   name: pass environment
                uses: appleboy/ssh-action@master
                env:
                    ROOT_DIR: "/home/izas/www/"
                    BRANCH: "master"
                    DEPLOY: "sh bin/deploy.sh www"
                    COMPOSER: "/usr/sbin/container-run oxeva/php-7.2-gw php -dmemory_limit=2048M /home/izas/composer.phar"
                with:
                    host: ${{ secrets.HOST }}
                    username: ${{ secrets.USERNAME }}
                    password: ${{ secrets.PASSWORD }}
                    port: ${{ secrets.PORT }}
                    envs: ROOT_DIR,BRANCH,DEPLOY,COMPOSER
                    script: |
                        cd $ROOT_DIR
                        git fetch
                        git checkout $BRANCH
                        git pull
                        $COMPOSER install -vv
                        $DEPLOY
                        sh bin/flush-all.sh www
